on:
  push:
    tags:
      - 'v*'
name: Release

jobs:
  releases:
    name: Upload build files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      - name: Build
        run: yarn build
      - Upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: jquery.marker-animation.min.js
          asset_name: jquery.marker-animation.min.js
          tag: ${{ github.ref }}
          overwrite: true
